inherit_gem:
  caliber: config/all.yml

Gemspec/RequiredRubyVersion:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
Layout/RedundantLineBreak:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
RSpec/FilePath:
  Exclude:
    - "spec/support/fixtures/**/*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/support/fixtures/**/*"
