inherit_gem:
  caliber: config/all.yml

Gemspec/RequiredRubyVersion:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
Layout/RedundantLineBreak:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/gemsmith/cli/commands/build.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/gemsmith/cli/shell.rb"
RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/support/fixtures/**/*"
RSpec/SpecFilePathSuffix:
  Exclude:
    - "spec/support/fixtures/**/*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/support/fixtures/**/*"
